region = "us-west-2"
profile = "default"
availability_zone = "us-west-2a"
instance_type = "t2.nano"
key_name = "burpkeypair"
server_name = "burp" # used to set the hostname on the linux box
zone = "asdfj.click"
burp_zone = "collab" # This will result in burp-collaborator.anshumanbhartiya.com
permitted_ssh_cidr_block = "0.0.0.0/0" # It is recommend this is changed to your IP to prevent noise from SSH scanners
name = "LE"
email_address = "null@asdfj.click"
hosted_zone_id = "asdfj.click"
